# Generated by Django 5.1.6 on 2025-03-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploader_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
