# Generated by Django 5.1.6 on 2025-03-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_collection'),
        ('books', '0003_book_uploader_email'),
    ]

    operations = [
    ]
