# Generated by Django 5.1.6 on 2025-04-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_borrowed_at_remove_book_borrowed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateField(),
        ),
    ]
