# Generated by Django 5.1.6 on 2025-04-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrowerreview_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(choices=[('Brown Library', 'Brown Library'), ('Clemons Library', 'Clemons Library'), ('Fine Arts Library', 'Fine Arts Library'), ('Harrison/Small Library', 'Harrison/Small Library'), ('Music Library', 'Music Library'), ('Shannon Library', 'Shannon Library'), ('TBD', 'TBD')], default='TBD', max_length=25),
        ),
    ]
