# Generated by Django 5.1.6 on 2025-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_collectionaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaccessrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
