# Generated by Django 5.1.6 on 2025-04-29 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_bookreview_delete_borrowhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='borrow_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_request', to='books.borrowrequest'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
