# Generated by Django 5.1.6 on 2025-04-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_bookreview_book_alter_bookreview_borrow_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='borrow_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='books.borrowrequest'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
