name: Django CI

on:
  # Run on every push to the repository and on pull requests
  push:
    branches: [ main, develop, testing-branch, my-templates ]  # Change for main
  pull_request:
    branches: [ main, develop, testing-branch, my-templates ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test accounts
